package auditor

// GetDefaultCVEDatabase returns embedded container breakout & kernel escalation CVE rules.
func GetDefaultCVEDatabase() *CVEDatabase {
	return &CVEDatabase{
		LastUpdated: "2026-07-28 21:00:00 UTC",
		Rules: []CVERule{
			// --- RUNC & BUILDKIT (LEAKY VESSELS) ---
			{
				CVE: CVEFinding{
					ID:            "CVE-2024-21626",
					Title:         "Leaky Vessels: runc Host Directory File Descriptor Leak Escape",
					Severity:      "CRITICAL",
					CVSSScore:     8.6,
					Component:     "runc / containerd / Docker",
					Description:   "An internal host directory file descriptor is leaked into container processes via openat2 upon container startup or execution. An attacker inside the container can traverse the leaked FD to gain full read/write access to the host root filesystem.",
					ExploitVector: "Leaked host directory file descriptor in /proc/[pid]/fd",
					Mitigation:    "Upgrade runc to >= 1.1.12. Ensure processes close inherited host directory descriptors prior to container exec (O_CLOEXEC).",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2024-21626",
					References: []string{
						"https://snyk.io/blog/leaky-vessels-docker-runc-container-breakout-vulnerabilities/",
						"https://github.com/opencontainers/runc/security/advisories/GHSA-xr7r-f8xq-vfvv",
					},
				},
				RequireHostFDLeak: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2024-21627",
					Title:         "Leaky Vessels: runc Container Escape via /proc/self/fd Traversal",
					Severity:      "HIGH",
					CVSSScore:     7.8,
					Component:     "runc / Docker",
					Description:   "Insecure handling of working directory file descriptors allows a container process to access host root by referencing /proc/self/fd/ descriptors during container initialization.",
					ExploitVector: "Host directory FD leak in /proc/self/fd",
					Mitigation:    "Upgrade runc to >= 1.1.12 and containerd to >= 1.6.28.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2024-21627",
					References: []string{
						"https://github.com/opencontainers/runc/security/advisories/GHSA-g2j6-57v7-gm8c",
					},
				},
				RequireHostFDLeak: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2024-21628",
					Title:         "Leaky Vessels: runc Process Working Directory Mount Trap Escape",
					Severity:      "HIGH",
					CVSSScore:     7.5,
					Component:     "runc / Docker",
					Description:   "Container process working directory set to a path pointing to host directory allows containerized process to trick runtime into exposing host filesystem.",
					ExploitVector: "Host working directory descriptor exposure",
					Mitigation:    "Upgrade runc to >= 1.1.12.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2024-21628",
					References: []string{
						"https://github.com/opencontainers/runc/security/advisories/GHSA-2v6h-3q8p-hv2c",
					},
				},
				RequireHostFDLeak: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2024-23651",
					Title:         "BuildKit Mount /proc Access Host Breakout",
					Severity:      "CRITICAL",
					CVSSScore:     9.0,
					Component:     "Docker BuildKit",
					Description:   "BuildKit container builds allowing custom mounts can expose writable /proc filesystems during image build execution, allowing build-time code execution to escape to host root.",
					ExploitVector: "Writable /proc filesystem during container build/exec",
					Mitigation:    "Upgrade BuildKit to >= 0.12.5 or Docker Desktop to >= 4.27.0.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2024-23651",
					References: []string{
						"https://github.com/moby/buildkit/security/advisories/GHSA-5vcv-548h-gt5x",
					},
				},
				RequireWritableProc: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2024-23652",
					Title:         "BuildKit Mount create-dest Host Directory Removal",
					Severity:      "HIGH",
					CVSSScore:     8.2,
					Component:     "Docker BuildKit",
					Description:   "BuildKit mount processing allows subpaths to escape working directory boundaries and delete arbitrary files/directories on the host system during container cleanup.",
					ExploitVector: "Host bind mount processing without nosymfollow",
					Mitigation:    "Upgrade BuildKit to >= 0.12.5.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2024-23652",
					References: []string{
						"https://github.com/moby/buildkit/security/advisories/GHSA-4v38-bh8m-v25f",
					},
				},
				RequireHostRootEUID: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2024-23653",
					Title:         "BuildKit Security Entitlements Container Bypass",
					Severity:      "HIGH",
					CVSSScore:     7.7,
					Component:     "Docker BuildKit",
					Description:   "Custom BuildKit GRPC API calls allow bypassing container security entitlements (security.insecure), launching container builds with host root capabilities.",
					ExploitVector: "Unsanitized build entitlements + Host root EUID",
					Mitigation:    "Upgrade BuildKit to >= 0.12.5 and restrict GRPC API access.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2024-23653",
					References: []string{
						"https://github.com/moby/buildkit/security/advisories/GHSA-wr6v-9f75-vh25",
					},
				},
				RequireHostRootEUID: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2019-5736",
					Title:         "runc Container Breakout via /proc/self/exe Binary Overwrite",
					Severity:      "CRITICAL",
					CVSSScore:     8.6,
					Component:     "runc / Docker",
					Description:   "Allows a malicious container running as host EUID 0 without NoNewPrivileges to overwrite the host runc binary by opening /proc/self/exe during 'docker exec' invocation, granting host root command execution upon subsequent container runs.",
					ExploitVector: "Host EUID 0 + Writable /proc + Missing NoNewPrivileges",
					Mitigation:    "Enforce NoNewPrivileges=true, run containers as non-root UIDs, and upgrade runc to >= 1.0.0-rc6.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2019-5736",
					References: []string{
						"https://www.openwall.com/lists/oss-security/2019/02/11/2",
						"https://github.com/opencontainers/runc/commit/0a8e4117e7f715d5fdef3d94032137c0b69f4e3d",
					},
				},
				RequireHostRootEUID: true,
				RequireNoNewPrivsNo: true,
				RequireWritableProc: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2021-30465",
					Title:         "runc Mount Destination Symlink Exchange Breakout",
					Severity:      "HIGH",
					CVSSScore:     8.5,
					Component:     "runc / Docker",
					Description:   "A race condition during volume mount resolution allows a container process to swap a mount destination target path with a symlink pointing to a host path, writing files to the host filesystem.",
					ExploitVector: "Writable volume mounts + Missing nosymfollow flag",
					Mitigation:    "Upgrade runc to >= 1.0.0-rc95. Mount volumes with 'nosymfollow' and 'nodev'.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2021-30465",
					References: []string{
						"https://github.com/opencontainers/runc/security/advisories/GHSA-c3xm-pvg7-gh7r",
					},
				},
				RequireHostRootEUID: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2018-15664",
					Title:         "Docker Copy ('docker cp') Symlink Race Host Escape",
					Severity:      "HIGH",
					CVSSScore:     7.5,
					Component:     "Docker Engine",
					Description:   "A time-of-check to time-of-use (TOCTOU) race condition in 'docker cp' allows a container process to replace a copied destination path with a symlink pointing to a host file, overwriting arbitrary host root files.",
					ExploitVector: "Host EUID 0 + Writable root filesystem",
					Mitigation:    "Upgrade Docker Engine to >= 19.03.1 or avoid using 'docker cp' on untrusted containers.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2018-15664",
					References: []string{
						"https://github.com/moby/moby/issues/39292",
					},
				},
				RequireHostRootEUID: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2022-29162",
					Title:         "runc Exec User Capability Leak",
					Severity:      "HIGH",
					CVSSScore:     7.8,
					Component:     "runc / Docker",
					Description:   "When executing commands inside a container via runc exec with a custom user, inherited capability sets are not properly cleared, leaking elevated capabilities to non-root execution contexts.",
					ExploitVector: "Missing NoNewPrivileges + Inherited capabilities",
					Mitigation:    "Upgrade runc to >= 1.1.2 and set NoNewPrivileges=true.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2022-29162",
					References: []string{
						"https://github.com/opencontainers/runc/security/advisories/GHSA-7d76-8777-885q",
					},
				},
				RequireNoNewPrivsNo: true,
			},

			// --- CGROUP & DAEMON VULNERABILITIES ---
			{
				CVE: CVEFinding{
					ID:            "CVE-2022-0492",
					Title:         "cgroupv1 release_agent Container Breakout via CAP_SYS_ADMIN",
					Severity:      "HIGH",
					CVSSScore:     7.8,
					Component:     "Linux Kernel / cgroupv1",
					Description:   "A container running with CAP_SYS_ADMIN capability and writable cgroupv1 mount points can write a malicious release_agent script into /sys/fs/cgroup/release_agent. When cgroup processes terminate, the host kernel executes the script outside container boundaries as host root.",
					ExploitVector: "CAP_SYS_ADMIN + Writable /sys/fs/cgroup mount",
					Mitigation:    "Drop CAP_SYS_ADMIN capability, mount /sys/fs/cgroup read-only, or migrate host to cgroupv2.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2022-0492",
					References: []string{
						"https://unit42.paloaltonetworks.com/cve-2022-0492-cgroups/",
						"https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=24f60085f928227",
					},
				},
				RequireCAPSysAdmin: true,
				RequireWritableSys: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2020-15257",
					Title:         "containerd-shim Abstract Unix Socket Host Exposure",
					Severity:      "HIGH",
					CVSSScore:     7.5,
					Component:     "containerd",
					Description:   "When containers run sharing the host network namespace ('--net=host'), containerd-shim's abstract Unix domain sockets (@/containerd-shim/) become accessible to processes inside the container, allowing containerized processes to send commands directly to containerd-shim and launch new privileged host containers.",
					ExploitVector: "Shared host network namespace ('net' NS shared)",
					Mitigation:    "Do not share host network namespace (--net=host) with untrusted workloads. Upgrade containerd to >= 1.3.9 or >= 1.4.3.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2020-15257",
					References: []string{
						"https://github.com/containerd/containerd/security/advisories/GHSA-3647-864f-37fc",
						"https://www.benthamsgaze.org/2020/12/01/cve-2020-15257-containerd-shim-api-exposure/",
					},
				},
				RequireSharedNetNS:      true,
				RequireContainerized:    true,
				RequireContainerRuntime: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2022-0811",
					Title:         "cr8escape: CRI-O / crun Arbitrary Sysctl Host Overwrite",
					Severity:      "CRITICAL",
					CVSSScore:     8.8,
					Component:     "CRI-O / Kubernetes",
					Description:   "Flaw in CRI-O handling of pinns sysctl parameters allows malicious pods to pass sysctl keys containing '+' or '=' characters, writing arbitrary values to host kernel sysctls (e.g., kernel.core_pattern) and achieving host root command execution.",
					ExploitVector: "CAP_SYS_ADMIN + Writable /proc/sys interface",
					Mitigation:    "Upgrade CRI-O to >= 1.24.0 or >= 1.23.2.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2022-0811",
					References: []string{
						"https://blog.aquasec.com/cve-2022-0811-cri-o-vulnerability-cr8escape",
					},
				},
				RequireCAPSysAdmin:  true,
				RequireWritableProc: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2022-1227",
					Title:         "Podman podman top Container Escape via PS Syntax Injection",
					Severity:      "HIGH",
					CVSSScore:     8.8,
					Component:     "Podman",
					Description:   "Flaw in Podman handling of environment variables when running 'podman top' allows a container to manipulate output formatting strings and execute malicious binaries on the host system.",
					ExploitVector: "Host EUID 0 + Unsanitized environment variables",
					Mitigation:    "Upgrade Podman to >= 4.1.0.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2022-1227",
					References: []string{
						"https://bugzilla.redhat.com/show_bug.cgi?id=2070442",
					},
				},
				RequireHostRootEUID: true,
			},

			// --- KUBERNETES & KUBELET VULNERABILITIES ---
			{
				CVE: CVEFinding{
					ID:            "CVE-2021-25741",
					Title:         "Kubelet Subpath Volume Mount Symlink Host Escape",
					Severity:      "HIGH",
					CVSSScore:     8.1,
					Component:     "Kubernetes Kubelet",
					Description:   "A user with permissions to create Pods with subPath volume mounts can construct a symlink inside the volume pointing to a host directory, allowing the Pod to mount host root paths.",
					ExploitVector: "Host EUID 0 + Volume mounts without nosymfollow",
					Mitigation:    "Upgrade Kubelet to >= 1.22.2, 1.21.5, or 1.20.11.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2021-25741",
					References: []string{
						"https://github.com/kubernetes/kubernetes/issues/104980",
					},
				},
				RequireHostRootEUID: true,
				RequireKubernetes:   true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2023-5528",
					Title:         "Kubelet In-Tree Storage Volume Mount Path Traversal",
					Severity:      "HIGH",
					CVSSScore:     7.2,
					Component:     "Kubernetes Kubelet",
					Description:   "In-tree storage volume mount handling in Kubelet on Windows/Linux nodes allows path traversal characters in volume paths, allowing Pods to mount host directories.",
					ExploitVector: "Host EUID 0 + Insecure volume mount path",
					Mitigation:    "Upgrade Kubelet to >= 1.28.4, 1.27.8, or 1.26.11.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2023-5528",
					References: []string{
						"https://github.com/kubernetes/kubernetes/issues/121882",
					},
				},
				RequireHostRootEUID: true,
				RequireKubernetes:   true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2020-8554",
					Title:         "Kubernetes ExternalIP Service Man-in-the-Middle Exposure",
					Severity:      "MEDIUM",
					CVSSScore:     6.5,
					Component:     "Kubernetes API / kube-proxy",
					Description:   "Users with permissions to create or update Services can set spec.externalIPs to intercept traffic destined for other cluster services or external endpoints.",
					ExploitVector: "Shared host network namespace / exposed ports",
					Mitigation:    "Restrict spec.externalIPs via OPA Gatekeeper / Kyverno policy.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2020-8554",
					References: []string{
						"https://github.com/kubernetes/kubernetes/issues/97076",
					},
				},
				RequireSharedNetNS: true,
				RequireKubernetes:  true,
			},

			// --- KERNEL PRIVILEGE ESCALATION ---
			{
				CVE: CVEFinding{
					ID:            "CVE-2022-0847",
					Title:         "Dirty Pipe: Host Kernel Memory Write via Writable Pipe FDs",
					Severity:      "CRITICAL",
					CVSSScore:     7.8,
					Component:     "Linux Kernel (5.8 - 5.16.11)",
					Description:   "Flaw in pipe buffer page flags allows unprivileged processes to write data into pagecache pages of arbitrary read-only host files (e.g. /etc/passwd or SUID binaries), granting instant root privilege escalation.",
					ExploitVector: "Unprivileged process + Writable pipe buffer FDs",
					Mitigation:    "Update host Linux kernel to >= 5.16.11, >= 5.15.25, or >= 5.10.102.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2022-0847",
					References: []string{
						"https://dirtypipe.cm4all.com/",
						"https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=9d2231c5d742",
					},
				},
				RequireUnprivUserNS: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2023-4911",
					Title:         "Looney Tunables: GLIBC_TUNABLES Buffer Overflow Root Escalation",
					Severity:      "HIGH",
					CVSSScore:     7.8,
					Component:     "glibc / Linux Kernel",
					Description:   "Buffer overflow in GNU C Library dynamic loader (ld.so) processing of GLIBC_TUNABLES environment variable allows local unprivileged users to execute arbitrary code as host root via SUID binaries.",
					ExploitVector: "Active SUID binaries + Missing NoNewPrivileges flag",
					Mitigation:    "Update glibc packages to patched security release and set NoNewPrivileges=true.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2023-4911",
					References: []string{
						"https://www.qualys.com/2023/10/03/cve-2023-4911/looney-tunables-local-privilege-escalation-glibc-ld-so.txt",
					},
				},
				RequireSUIDBinaries: true,
				RequireNoNewPrivsNo: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2021-3156",
					Title:         "Baron Samedit: Sudo Heap-Based Buffer Overflow Escalation",
					Severity:      "HIGH",
					CVSSScore:     7.8,
					Component:     "sudo / Linux Kernel",
					Description:   "Heap-based buffer overflow in sudo handling of command line arguments in shell mode ('sudoedit -s') allows any unprivileged user inside a container or host to obtain root privileges.",
					ExploitVector: "Active SUID binaries (/usr/bin/sudo) + EUID != 0",
					Mitigation:    "Update sudo package to >= 1.9.5p2 or remove SUID bit from sudo binary inside container images.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2021-3156",
					References: []string{
						"https://www.qualys.com/2021/01/26/cve-2021-3156/baron-samedit-heap-based-buffer-overflow-sudo.txt",
					},
				},
				RequireSUIDBinaries: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2021-3493",
					Title:         "OverlayFS Unprivileged User Namespace Privilege Escalation",
					Severity:      "HIGH",
					CVSSScore:     7.8,
					Component:     "Linux Kernel / OverlayFS",
					Description:   "An unprivileged user inside a user namespace can mount an OverlayFS filesystem on Ubuntu/Debian kernels and manipulate file capabilities/SUID flags on host-backed lowerdir mounts, escalating privileges to host root.",
					ExploitVector: "Unprivileged user namespace clone enabled + OverlayFS mount",
					Mitigation:    "Disable unprivileged user namespace cloning ('sysctl -w kernel.unprivileged_userns_clone=0') or update kernel to patched release.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2021-3493",
					References: []string{
						"https://github.com/briskapex/cve-2021-3493",
						"https://ubuntu.com/security/CVE-2021-3493",
					},
				},
				RequireUnprivUserNS: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2023-2640",
					Title:         "GameOver(lay): Ubuntu Kernel OverlayFS SUID Copy Escalation",
					Severity:      "HIGH",
					CVSSScore:     7.8,
					Component:     "Ubuntu Linux Kernel / OverlayFS",
					Description:   "Ubuntu-specific modifications to OverlayFS allow unprivileged user namespaces to copy file capabilities without scrubbing dangerous security attributes, enabling local root escalation.",
					ExploitVector: "Unprivileged user namespace + OverlayFS",
					Mitigation:    "Update Ubuntu kernel to latest security release. Restrict unprivileged user namespaces.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2023-2640",
					References: []string{
						"https://wiz.io/blog/ubuntu-overlayfs-vulnerabilities-gameover-lay",
					},
				},
				RequireUnprivUserNS: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2023-32629",
					Title:         "GameOver(lay): Ubuntu Kernel OverlayFS Privilege Escalation",
					Severity:      "HIGH",
					CVSSScore:     7.8,
					Component:     "Ubuntu Linux Kernel / OverlayFS",
					Description:   "Companion vulnerability in Ubuntu OverlayFS implementation allowing unauthorized file attribute copies leading to local privilege escalation.",
					ExploitVector: "Unprivileged user namespace + OverlayFS",
					Mitigation:    "Update Ubuntu kernel to latest security release.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2023-32629",
					References: []string{
						"https://ubuntu.com/security/CVE-2023-32629",
					},
				},
				RequireUnprivUserNS: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2021-33909",
					Title:         "Sequoia: Filesystem size_t Overflow Kernel Privilege Escalation",
					Severity:      "HIGH",
					CVSSScore:     7.8,
					Component:     "Linux Kernel / VFS",
					Description:   "Size_t integer overflow in filesystem path handling in Linux kernel VFS layer allows an unprivileged local user to execute arbitrary code as kernel root.",
					ExploitVector: "Unprivileged user context + Deep directory creation",
					Mitigation:    "Update Linux kernel to patched release.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2021-33909",
					References: []string{
						"https://www.qualys.com/2021/07/20/cve-2021-33909/sequoia-local-privilege-escalation-linux-kernel.txt",
					},
				},
				RequireUnprivUserNS: true,
			},

			// --- EBPF & SYSCTL VULNERABILITIES ---
			{
				CVE: CVEFinding{
					ID:            "CVE-2023-2163",
					Title:         "eBPF Verifier Kernel Memory Exposure & Privilege Escalation",
					Severity:      "HIGH",
					CVSSScore:     7.8,
					Component:     "Linux Kernel eBPF",
					Description:   "Improper state tracking in the Linux kernel eBPF verifier allows unprivileged or CAP_BPF processes to bypass eBPF verifier checks, causing out-of-bounds reads and writes in host kernel memory.",
					ExploitVector: "CAP_BPF / CAP_SYS_ADMIN or unprivileged eBPF enabled",
					Mitigation:    "Set 'sysctl -w kernel.unprivileged_bpf_disabled=1' or '2' and drop CAP_BPF / CAP_SYS_ADMIN capabilities.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2023-2163",
					References: []string{
						"https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=7105e828c087",
						"https://kernel.org/doc/html/latest/admin-guide/sysctl/kernel.html#unprivileged-bpf-disabled",
					},
				},
				RequireCAPBPF: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2021-3490",
					Title:         "eBPF ALU32 Bounds Tracking Kernel Escalation",
					Severity:      "HIGH",
					CVSSScore:     7.8,
					Component:     "Linux Kernel eBPF",
					Description:   "32-bit ALU bounds tracking in eBPF verifier allows crafted eBPF programs to bypass verification and perform arbitrary kernel memory modification.",
					ExploitVector: "CAP_BPF / CAP_SYS_ADMIN capability active",
					Mitigation:    "Disable unprivileged eBPF ('sysctl kernel.unprivileged_bpf_disabled=1') and update kernel.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2021-3490",
					References: []string{
						"https://www.openwall.com/lists/oss-security/2021/05/11/11",
					},
				},
				RequireCAPBPF: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2022-23222",
					Title:         "eBPF BPF_RINGBUF Out-of-Bounds Kernel Escalation",
					Severity:      "HIGH",
					CVSSScore:     7.8,
					Component:     "Linux Kernel eBPF",
					Description:   "Improper pointer arithmetic validation in eBPF verifier for BPF_RINGBUF map types allows local attackers to write to arbitrary kernel memory.",
					ExploitVector: "CAP_BPF / CAP_SYS_ADMIN capability active",
					Mitigation:    "Set 'sysctl -w kernel.unprivileged_bpf_disabled=1' and update kernel.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2022-23222",
					References: []string{
						"https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=c25b2d9f4035",
					},
				},
				RequireCAPBPF: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2020-27194",
					Title:         "eBPF Verifier Scalar Bounds Tracking Kernel Escalation",
					Severity:      "HIGH",
					CVSSScore:     7.8,
					Component:     "Linux Kernel eBPF",
					Description:   "Flaw in eBPF verifier scalar bounds calculation allows out-of-bounds read and write operations in kernel memory.",
					ExploitVector: "CAP_BPF / CAP_SYS_ADMIN active",
					Mitigation:    "Update Linux kernel and disable unprivileged eBPF.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2020-27194",
					References: []string{
						"https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=5b0ab78998e3",
					},
				},
				RequireCAPBPF: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2017-5123",
					Title:         "waitid ptrace Kernel Memory Overwrite Vulnerability",
					Severity:      "HIGH",
					CVSSScore:     7.8,
					Component:     "Linux Kernel",
					Description:   "Insufficient access checks in the waitid(2) syscall allow processes with ptrace rights or unconfined ptrace scope to write zero bytes into arbitrary kernel memory addresses.",
					ExploitVector: "CAP_SYS_PTRACE + Unrestricted YAMA ptrace scope",
					Mitigation:    "Set 'sysctl -w kernel.yama.ptrace_scope=1' or higher and drop CAP_SYS_PTRACE capability.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2017-5123",
					References: []string{
						"https://github.com/sultanqasim/CVE-2017-5123",
						"https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4c48b71d9d9",
					},
				},
				RequireCAPPtrace: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2022-0185",
					Title:         "Legacy fsconfig Heap Overflow Kernel Privilege Escalation",
					Severity:      "HIGH",
					CVSSScore:     7.8,
					Component:     "Linux Kernel / Filesystem",
					Description:   "Heap-based buffer overflow in legacy_parse_param in the Linux kernel filesystem context allows local unprivileged users with CAP_SYS_ADMIN in a user namespace to escalate to root.",
					ExploitVector: "CAP_SYS_ADMIN capability active",
					Mitigation:    "Disable unprivileged user namespaces and update host kernel.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2022-0185",
					References: []string{
						"https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=722d62057f",
					},
				},
				RequireCAPSysAdmin: true,
			},

			// --- NETFILTER & NETWORKING VULNERABILITIES ---
			{
				CVE: CVEFinding{
					ID:            "CVE-2024-1086",
					Title:         "nf_tables Use-After-Free Kernel Privilege Escalation",
					Severity:      "CRITICAL",
					CVSSScore:     7.8,
					Component:     "Linux Kernel / Netfilter",
					Description:   "Use-after-free vulnerability in Linux kernel's netfilter: nf_tables component allows local unprivileged users with CAP_NET_ADMIN / CAP_NET_RAW or unprivileged user namespaces to achieve local root privilege escalation.",
					ExploitVector: "CAP_NET_ADMIN / CAP_NET_RAW or unprivileged user namespace",
					Mitigation:    "Update Linux kernel to patched release. Set 'sysctl -w kernel.unprivileged_userns_clone=0'.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2024-1086",
					References: []string{
						"https://github.com/Notsfsssf/CVE-2024-1086",
						"https://pwning.tech/nftables/",
					},
				},
				RequireCAPNetAdmin: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2023-31248",
					Title:         "nf_tables nft_chain Use-After-Free Privilege Escalation",
					Severity:      "HIGH",
					CVSSScore:     7.8,
					Component:     "Linux Kernel / Netfilter",
					Description:   "A use-after-free vulnerability in netfilter (nf_tables) allows local users with CAP_NET_ADMIN in any user namespace to gain elevated kernel execution.",
					ExploitVector: "CAP_NET_ADMIN / CAP_NET_RAW active",
					Mitigation:    "Update Linux kernel to patched security release.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2023-31248",
					References: []string{
						"https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=7a03231362d",
					},
				},
				RequireCAPNetAdmin: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2022-25636",
					Title:         "nf_tables Heap Out-of-Bounds Write Escalation",
					Severity:      "HIGH",
					CVSSScore:     7.8,
					Component:     "Linux Kernel / Netfilter",
					Description:   "Heap out-of-bounds write in netfilter (nft_payload_copy_vlan) allows local attacker with CAP_NET_ADMIN to write beyond heap buffer bounds, leading to root privilege escalation.",
					ExploitVector: "CAP_NET_ADMIN active",
					Mitigation:    "Drop CAP_NET_ADMIN capability and update host kernel.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2022-25636",
					References: []string{
						"https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b8fe142079a",
					},
				},
				RequireCAPNetAdmin: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2022-34918",
					Title:         "nf_tables nft_set_elem_init Heap Buffer Overflow Escalation",
					Severity:      "HIGH",
					CVSSScore:     7.8,
					Component:     "Linux Kernel / Netfilter",
					Description:   "Heap buffer overflow in netfilter nft_set_elem_init allows local user with CAP_NET_ADMIN capability to achieve kernel privilege escalation.",
					ExploitVector: "CAP_NET_ADMIN capability active",
					Mitigation:    "Update kernel to >= 5.18.13.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2022-34918",
					References: []string{
						"https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=7e6ef1203e0a",
					},
				},
				RequireCAPNetAdmin: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2023-0179",
					Title:         "nf_tables VLAN Header Parsing Buffer Overflow Escalation",
					Severity:      "HIGH",
					CVSSScore:     7.8,
					Component:     "Linux Kernel / Netfilter",
					Description:   "Buffer overflow vulnerability in netfilter nft_payload_copy_vlan when parsing VLAN headers, allowing local root escalation.",
					ExploitVector: "CAP_NET_ADMIN active",
					Mitigation:    "Update kernel to patched release.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2023-0179",
					References: []string{
						"https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=696e1a48b1c1",
					},
				},
				RequireCAPNetAdmin: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2021-22555",
					Title:         "Netfilter IPT_SO_SET_REPLACE Out-of-Bounds Write Escalation",
					Severity:      "HIGH",
					CVSSScore:     7.8,
					Component:     "Linux Kernel / Netfilter",
					Description:   "Out-of-bounds write in xt_compat_target_from_user in Netfilter allows local users with CAP_NET_ADMIN to overwrite kernel memory and escape container isolation.",
					ExploitVector: "CAP_NET_ADMIN active",
					Mitigation:    "Update kernel to >= 5.12. Restrict CAP_NET_ADMIN.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2021-22555",
					References: []string{
						"https://google.github.io/security-research/pocs/linux/cve-2021-22555/writeup.html",
					},
				},
				RequireCAPNetAdmin: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2020-14386",
					Title:         "CAP_NET_RAW Packet Socket Memory Corruption Escalation",
					Severity:      "HIGH",
					CVSSScore:     7.8,
					Component:     "Linux Kernel / Networking",
					Description:   "An out-of-bounds write in net/packet/af_packet.c allows a process with CAP_NET_RAW (or in a container with raw socket permissions) to trigger kernel memory corruption and gain root privileges.",
					ExploitVector: "CAP_NET_RAW capability active inside container",
					Mitigation:    "Drop CAP_NET_RAW capability from container runtimes.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2020-14386",
					References: []string{
						"https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=acf69c946233259e196f38799",
					},
				},
				RequireCAPNetRaw: true,
			},
			{
				CVE: CVEFinding{
					ID:            "CVE-2024-26923",
					Title:         "af_unix Socket Use-After-Free Kernel Privilege Escalation",
					Severity:      "HIGH",
					CVSSScore:     7.8,
					Component:     "Linux Kernel / Networking",
					Description:   "Use-after-free vulnerability in AF_UNIX socket implementation allows local unprivileged process to gain kernel root execution.",
					ExploitVector: "Unprivileged user context + Unix sockets",
					Mitigation:    "Update Linux kernel to patched security release.",
					URL:           "https://nvd.nist.gov/vuln/detail/CVE-2024-26923",
					References: []string{
						"https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=87ef6722d56a",
					},
				},
				RequireUnprivUserNS: true,
			},
		},
	}
}
