package auditor

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// RemediationArtifacts holds auto-generated configuration files and code snippets.
type RemediationArtifacts struct {
	SystemdOverridePath string   `json:"systemd_override_path,omitempty"`
	SystemdOverride     string   `json:"systemd_override,omitempty"`
	DockerCLI           string   `json:"docker_cli,omitempty"`
	DockerCompose       string   `json:"docker_compose,omitempty"`
	KubernetesYAML      string   `json:"kubernetes_yaml,omitempty"`
	SysctlConf          string   `json:"sysctl_conf,omitempty"`
	SysctlCommands      []string `json:"sysctl_commands,omitempty"`
}

// GenerateRemediations evaluates an AuditReport and constructs actionable hardening snippets.
func GenerateRemediations(r *AuditReport) *RemediationArtifacts {
	artifacts := &RemediationArtifacts{}

	// 1. Systemd Service Drop-in Override Generator
	if r.Systemd != nil && r.Systemd.UnitName != "" {
		unitName := r.Systemd.UnitName
		var lines []string
		lines = append(lines, "# Auto-generated by nspect security auditor")
		lines = append(lines, fmt.Sprintf("# Save to /etc/systemd/system/%s.d/override.conf", unitName))
		lines = append(lines, "[Service]")

		for _, d := range r.Systemd.Directives {
			if !d.IsSecure && d.RecommendedValue != "" {
				lines = append(lines, fmt.Sprintf("%s=%s", d.Name, d.RecommendedValue))
			}
		}

		if len(lines) > 3 {
			artifacts.SystemdOverride = strings.Join(lines, "\n") + "\n"
			artifacts.SystemdOverridePath = fmt.Sprintf("/etc/systemd/system/%s.d/override.conf", unitName)
		}
	}

	// 2. Docker CLI & Compose & Kubernetes Generators
	procName := strings.ToLower(r.ProcessName)
	if procName == "" {
		procName = "app"
	}

	// Determine required capabilities to add
	var capsToAdd []string
	if r.Capabilities != nil {
		for _, capName := range r.Capabilities.Sets.Effective {
			if capName == "CAP_NET_BIND_SERVICE" || capName == "CAP_NET_ADMIN" || capName == "CAP_NET_RAW" {
				capsToAdd = append(capsToAdd, capName)
			}
		}
	}

	capAddDockerStr := ""
	capAddComposeLines := ""
	capAddK8sLines := ""
	for _, capName := range capsToAdd {
		capAddDockerStr += fmt.Sprintf(" \\\n  --cap-add=%s", capName)
		capAddComposeLines += fmt.Sprintf("\n      - %s", capName)
		capAddK8sLines += fmt.Sprintf("\n            - %s", capName)
	}

	// Docker CLI Run Command
	dockerCLILines := []string{
		fmt.Sprintf("docker run -d --name %s-hardened \\", procName),
		"  --security-opt no-new-privileges:true \\",
		"  --read-only \\",
		"  --user 10001:10001 \\",
		"  --cap-drop=ALL" + capAddDockerStr + " \\",
		"  --memory=512m \\",
		"  --cpus=1.0 \\",
		"  --tmpfs /tmp:rw,noexec,nosuid \\",
		fmt.Sprintf("  %s:latest", procName),
	}
	artifacts.DockerCLI = strings.Join(dockerCLILines, "\n")

	// Docker Compose Service Snippet
	dockerComposeLines := []string{
		fmt.Sprintf("  %s:", procName),
		fmt.Sprintf("    image: %s:latest", procName),
		"    user: \"10001:10001\"",
		"    read_only: true",
		"    security_opt:",
		"      - no-new-privileges:true",
		"    cap_drop:",
		"      - ALL",
	}
	if len(capsToAdd) > 0 {
		dockerComposeLines = append(dockerComposeLines, "    cap_add:"+capAddComposeLines)
	}
	dockerComposeLines = append(dockerComposeLines,
		"    tmpfs:",
		"      - /tmp:rw,noexec,nosuid",
		"    deploy:",
		"      resources:",
		"        limits:",
		"          cpus: '1.0'",
		"          memory: 512M",
	)
	artifacts.DockerCompose = strings.Join(dockerComposeLines, "\n")

	// Kubernetes SecurityContext YAML Snippet
	k8sLines := []string{
		"apiVersion: apps/v1",
		"kind: Deployment",
		"metadata:",
		fmt.Sprintf("  name: %s-hardened", procName),
		"spec:",
		"  template:",
		"    spec:",
		"      securityContext:",
		"        runAsNonRoot: true",
		"        runAsUser: 10001",
		"        runAsGroup: 10001",
		"        seccompProfile:",
		"          type: RuntimeDefault",
		"      containers:",
		fmt.Sprintf("      - name: %s", procName),
		fmt.Sprintf("        image: %s:latest", procName),
		"        securityContext:",
		"          allowPrivilegeEscalation: false",
		"          readOnlyRootFilesystem: true",
		"          capabilities:",
		"            drop:",
		"            - ALL",
	}
	if len(capsToAdd) > 0 {
		k8sLines = append(k8sLines, "            add:"+capAddK8sLines)
	}
	artifacts.KubernetesYAML = strings.Join(k8sLines, "\n")

	// 3. Sysctl Hardening Artifacts
	if r.Kernel != nil && len(r.Kernel.Sysctls) > 0 {
		var sysctlConfLines []string
		var sysctlCmds []string
		sysctlConfLines = append(sysctlConfLines, "# Auto-generated by nspect security auditor")
		sysctlConfLines = append(sysctlConfLines, "# Save to /etc/sysctl.d/99-nspect-hardening.conf")

		for _, sys := range r.Kernel.Sysctls {
			if !sys.IsSecure && sys.ExpectedValue != "" {
				sysctlConfLines = append(sysctlConfLines, fmt.Sprintf("%s = %s", sys.Key, sys.ExpectedValue))
				sysctlCmds = append(sysctlCmds, fmt.Sprintf("sudo sysctl -w %s=%s", sys.Key, sys.ExpectedValue))
			}
		}

		if len(sysctlConfLines) > 2 {
			artifacts.SysctlConf = strings.Join(sysctlConfLines, "\n") + "\n"
			artifacts.SysctlCommands = sysctlCmds
		}
	}

	return artifacts
}

// ApplySystemdOverride writes the generated systemd override snippet to /etc/systemd/system/<unit>.service.d/override.conf
func ApplySystemdOverride(artifacts *RemediationArtifacts) (string, error) {
	if artifacts == nil || artifacts.SystemdOverride == "" || artifacts.SystemdOverridePath == "" {
		return "", fmt.Errorf("no systemd override snippet available to apply")
	}

	dir := filepath.Dir(artifacts.SystemdOverridePath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", fmt.Errorf("failed creating directory %s: %w", dir, err)
	}

	if err := os.WriteFile(artifacts.SystemdOverridePath, []byte(artifacts.SystemdOverride), 0600); err != nil {
		return "", fmt.Errorf("failed writing override file %s: %w", artifacts.SystemdOverridePath, err)
	}

	return artifacts.SystemdOverridePath, nil
}
